name: TDP_SiMPull_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - loguru
  - scikit-image
  - scipy
  - statsmodels
  - pingouin
  - plotly
  - pip
  - pip:
      - statannotations
